config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  devise_for :users
  root 'posts#index'

  resources :users do
    get "show"
    patch 'change_admin'
  end

  resources :posts do
    get 'best_posts', on: :collection
    get 'newest_posts', on: :collection
    resources :comments do
      patch "like"
      patch "dislike"
      patch "toggle_visible"
      patch "toggle_valid"
    end
  end
  
  resources :albums do
    match :posts, via: [:get, :patch], on: :member#get 'posts_list', :as => 'posts_list'
  end

  get 'posts/filter/:tag_name' => 'posts#filter', as: 'filter'

   get 'posts/filter_best/:tag_name' => 'posts#filter_best', as: 'filter_best'

end

app/models/user.rb
class User < ActiveRecord::Base
  ratyrate_rater
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :albums, dependent: :destroy
  has_many :likes, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  #paperclip
  has_attached_file :avatar, styles: { medium: "128x128>", thumb: "48x48>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

  def self.users_post_rating(user_id)
    q = "select p.id, r.stars, r.rateable_id, p.title, p.description, p.photo_file_name, p.photo_content_type, p.description
   FROM rates r, rating_caches rc, posts p where r.rater_id = #{user_id} and r.rateable_id = rc.cacheable_id and p.id = rc.cacheable_id;"
    ActiveRecord::Base.connection.execute(q)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  load_and_authorize_resource
  # sqlite3 db/development.sqlite3

  def index
    @users = User.all
  end

  def show
    user = User.find_by_id(params[:user_id])
    if user != nil
      @posts = user.posts.all
      @rating = User.users_post_rating(user.id)
    else
      redirect_to '/', :flash => { :notice => "There is no such user !" }
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy

    if @user.destroy
        redirect_to '/users', notice: "User deleted."
    end    
  end

  def change_admin
    @user = User.find_by_id(params[:user_id])
    @user.update_attribute(:admin, not(@user.admin?))
    redirect_to '/users', notice: 'Status of user changed.'
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.erb
<h3> List of users </h3>
<div class="row">

  <div class="col-lg-12">

<table class="table">
  <tr>
    <th>Avatar</th>
    <th>E-mail</th>
    <th>Admin</th>
  </tr>

  <% @users.each do |user| %>
    <tr id="user-row-<%= user.id %>">
      <td class=""><%= image_tag user.avatar.url(:thumb) %> </td>
      <td class="user-email"><p class="picture_info"><%= user.email %></p></td>
      <td class="user-admin"><p class="picture_info"><%= user.admin? ? 'yes' : 'no' %></p></td>
      <% if can? :update, user %><td><%= link_to user.admin? ? 'Change to normal user' : 'Change to admin', user_change_admin_path(user.id), :method => 'patch' %></td><% end %>
      <% if can? :delete, user %><td><%= link_to 'Delete', user_path(user),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td><% end %>
      <% if can? :read, user %><td><%= link_to 'Show', user_show_path(user) %></td><% end %>
    </tr>
  <% end %>
</table>
</div>
</div>

app/views/users/show.html.erb
<!-- Page Content -->
<div class="container">

  <div class="row">

    <div class="col-lg-12">
      <h1 class="page-header">User's photos</h1>
      <% @posts.each do |post| %>
          <div class="col-lg-3 col-md-4 col-xs-6 thumb">

            <div class="thumbnail">
              <h4><%= post.title %></h4>
              <%= link_to (image_tag post.photo.url(:thumb)), post_path(post) %>
              <p><%= post.description %></p>
              <div><% if can? :update, post %><%= link_to 'Edit', edit_post_path(post) %><% end %></div>
              <div><% if can? :delete, post %><%= link_to 'Delete', post_path(post),
                                                          method: :delete,
                                                          data: { confirm: 'Are you sure?' } %><% end %>
              </div>
            </div>
          </div>

      <% end %>
    </div>

    <div class="col-lg-12">
      <h1 class="page-header">User's favorites</h1>
      <% @rating.each do |post| %>
          <div class="col-lg-3 col-md-4 col-xs-6 thumb">
            <div class="thumbnail">
              <h4><%= post['title'] %></h4>
              <%= link_to (image_tag Post.find(post['id']).photo.url(:thumb)), post_path(post['id']) %>
              <p><%= post['description'] %></p>
              <p>Rating: <%= post['stars'] %></p>
              </div>
            </div>
      <% end %>
    </div>

  </div>
</div>