config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  devise_for :users
  root 'posts#index'

  resources :users do
    get "show"
    patch 'change_admin'
  end

  resources :posts do
    get 'best_posts', on: :collection
    get 'newest_posts', on: :collection
    resources :comments do
      patch "like"
      patch "dislike"
      patch "toggle_visible"
      patch "toggle_valid"
    end
  end
  
  resources :albums do
    match :posts, via: [:get, :patch], on: :member#get 'posts_list', :as => 'posts_list'
  end

  get 'posts/filter/:tag_name' => 'posts#filter', as: 'filter'

   get 'posts/filter_best/:tag_name' => 'posts#filter_best', as: 'filter_best'

end

app/models/album.rb
class Album < ActiveRecord::Base
  has_many :posts, dependent: :destroy
  belongs_to :user
  validates :title, :description, presence: true

  def rating
    posts_with_rating = self.posts.select { |post| post.rated? } unless self.posts.nil?
    return 0 if posts_with_rating.blank?
    sum = 0
    posts_with_rating.each { |post| sum += post.rating}
    sum / posts_with_rating.size.to_f
  end
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_filter :authenticate_user!
  load_and_authorize_resource

  def index
    @albums = current_user.admin? ? Album.all : Album.where(user_id: current_user.id).order('updated_at DESC')
  end

  def new
    @album = Album.new
  end

  def edit
    @album = Album.find(params[:id])
  end

  def create
    @album = Album.new(album_params)
    @album.user = current_user
    if @album.save
      redirect_to '/albums'
    else
      render 'new'
    end
  end

  def update
    @album = Album.find(params[:id])
    if @album.update(album_params)
      redirect_to '/albums'
    else
      render 'edit'
    end
  end

  def destroy
    @album = Album.find(params[:id])
    @album.destroy
    redirect_to '/albums'
  end

  def posts
    @album = Album.find(params[:id])
    @posts = Post.where(user_id: @album.user_id).where.not(album_id: @album.id).order('updated_at DESC') if request.get?
    if request.patch?
      album_params['post_ids'].select { |id| id != '-1' }.each do |post_id|
        Post.find(post_id).update_attribute('album_id', @album.id)
      end
      redirect_to '/albums/' + params[:id]
    end

  end

  private

  def album_params
    params.require(:album).permit(:title, :description, post_ids: [])
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/views/albums/edit.html.erb
<h1>Edit Post</h1>
<%= form_for :album, url: album_path(@album), method: :patch do |f| %>
  <% if @album.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@album.errors.count, 'error') %> prohibited this post from being saved:
      </h2>
      <ul>
        <% @album.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p class="form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title, class:"form-control" %>
  </p>

  <p class="form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description, class:"form-control" %>
  </p>
 
  <p>
    <%= f.submit class:"btn btn-success"%>
  </p>
<% end %>

app/views/albums/index.html.erb
<%= image_tag current_user.avatar.url(:thumb) %> <p><%= current_user.email %></p>
<%= link_to 'Create new album', new_album_path, class: 'btn btn-success' %>
</br>
</br>
</br>
<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header">My albums</h1>
  </div>

<table class="table">
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>Photos</th>
    <th>Average rating</th>
  </tr>

  <% @albums.each do |album| %>
    <tr id="album-row-<%= album.id %>">
      <td class="album-title"><%= album.title %></td>
      <td class="album-description"><%= album.description %></td>
      <td class="album-posts"><%= album.posts.size unless album.posts.nil? %></td>
      <td class='album-rating'><%= album.rating %>
      <td><%= link_to 'Add photos', posts_album_path(album) %></td>
      <% if can? :update, album %><td><%= link_to 'Edit', edit_album_path(album) %></td><% end %>
      <% if can? :delete, album %><td><%= link_to 'Delete', album_path(album),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td><% end %>
      <% if can? :read, album %><td><%= link_to 'Show', album_path(album) %></td><% end %>
    </tr>
  <% end %>
</table>
</div>

app/views/albums/new.html.erb
<h1>New Album</h1>
<%= form_for :album, url:albums_path do |f| %>
  <% if @album.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@album.errors.count, 'error') %> prohibited this post from being saved:
      </h2>
      <ul>
        <% @album.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p class="form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title, class:"form-control" %>
  </p>

  <p class="form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description, class:"form-control" %>
  </p>

  <p class="form-group">
    <%= f.submit "Create album", class:"btn btn-success" %>
  </p>
<% end %>

app/views/albums/posts.html.erb
<h1>Posts</h1>
</br>
</br>
</br>
<div class="row">

  <div class="col-lg-12">
    <h1 class="page-header">Thumbnail Gallery</h1>
  </div>
<%= form_for :album, url: posts_album_path(@album), method: :patch do |f| %>
<table class="table">
  <tr>
    <th>Author</th>
    <th>Title</th>
    <th>Description</th>
    <th>Photo</th>
    <th>Album</th>
    <th>Tags</th>
  </tr>
  <%= hidden_field_tag "album[post_ids][]", '-1' %>
  <% @posts.each do |post| %>
    <tr id="post-row-<%= post.id %>">
      <td class="post-author"><%= image_tag post.user.avatar.url(:thumb) %> <p><%= post.user.email %></p></td>
      <td class="post-title"><%= post.title %></td>
      <td class="post-description"><%= post.description %></td>
      <td class="post-photo"><%= image_tag post.photo.url(:thumb) %></td>
      <td class="post-title"><%= link_to post.album.title, album_path(post.album) unless post.album.nil? %></td>
      <td class="post-tags"><%= post.tags.map { |tag| tag.name}.join(', ') %></td>
      <td class="post-comments"><%= post.allow_comments %></td>
      <td><%= check_box_tag :post_ids, post.id, @album.posts.include?(post), :name => 'album[post_ids][]' %></td>
<% end %>
    <%= f.submit class:"btn btn-success"%>
    </tr>
  <% end %>
</table>
</div>

app/views/albums/show.html.erb
<br>
<div class="text-right">
  <p>
    <%= image_tag @album.user.avatar.url(:thumb) %>

  <p><%= @album.user.email %></p>
  </p>
  <%= link_to 'My albums', albums_path, class: 'btn btn-success' %>
</div>

<br>
<br>
<p>
  <h3><%= @album.title %></h3>
</p>

<p>
  <%= @album.description %>
</p>
<br>
<table class="table">
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>Photo</th>
    <th>Tags</th>
  </tr>
  <% @album.posts.each do |post| %>
      <tr id="post-row-<%= post.id %>">
        <td class="post-title"><%= post.title %></td>
        <td class="post-description"><%= post.description %></td>
        <td class="post-photo"><%= image_tag post.photo.url(:thumb) %></td>
        <td class="post-tags"><%= post.tags.map { |tag| tag.name }.join(', ') %></td>
        <% if can? :update, post %>
            <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <% end %>
        <% if can? :delete, post %>
            <td><%= link_to 'Delete', post_path(post),
                            method: :delete,
                            data: {confirm: 'Are you sure?'} %></td>
        <% end %>
        <% if can? :read, post %>
            <td><%= link_to 'Show', post_path(post) %></td>
        <% end %>
      </tr>
  <% end %>
</table>