config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  devise_for :users
  root 'posts#index'

  resources :users do
    get "show"
    patch 'change_admin'
  end

  resources :posts do
    get 'best_posts', on: :collection
    get 'newest_posts', on: :collection
    resources :comments do
      patch "like"
      patch "dislike"
      patch "toggle_visible"
      patch "toggle_valid"
    end
  end
  
  resources :albums do
    match :posts, via: [:get, :patch], on: :member#get 'posts_list', :as => 'posts_list'
  end

  get 'posts/filter/:tag_name' => 'posts#filter', as: 'filter'

   get 'posts/filter_best/:tag_name' => 'posts#filter_best', as: 'filter_best'

end

app/models/post.rb
class Post < ActiveRecord::Base
  ratyrate_rateable 'quality'
  has_and_belongs_to_many :tags
  belongs_to :user
  belongs_to :album
  has_many :comments, dependent: :destroy
  attr_accessor :tags_string
  attr_accessor :album_name
  attr_accessor :body_file_name
  attr_accessor :body_content_type
  validates :title, :description, :allow_comments, :album_name, presence: true

  # rubocop:disable Metrics/LineLength
  has_attached_file :photo, styles: { medium: '800x600>', thumb: '100x100>' }, default_url: '/images/:style/missing.png'
  # rubocop:enable Metrics/LineLength


  # rubocop:disable Style/RegexpLiteral
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\Z/
  # rubocop:enable Style/RegexpLiteral

  validates :photo, attachment_presence: true

  validates :tags_string, presence: { message: 'must have at least one tag' }

  before_create :parse_tags, :parse_album, prepend: true
  #before_update :check_tags, prepend: true
  before_destroy :remove_tags, prepend: true
  def check_tags(old_tags)
      parse_tags
      self.touch
      deleted_tags = old_tags - tags_string.split(/[\s,]+/)
      puts 'Deleted tags: ' + deleted_tags.to_s
      deleted_tags.each { |tag| Tag.destroy_all('name' => tag) if Post.joins(:tags).where('tags.name' => tag).empty? }
  end

  def rated?
    not(self.average('quality').nil?)
  end

  def rating
    self.average('quality').nil? ? 0 : self.average('quality').avg
  end

  private

    def remove_tags
      tags.each do |tag|
        tags.delete(tag)
        Tag.destroy(tag) if Post.joins(:tags).where('tags.name' => tag[:name]).empty?
      end
    end

    def parse_tags
      tag_strings = tags_string.split(/[\s,]+/)
      tag_strings.each {|tag| puts tag}
      self.tags = []
      tag_strings.uniq.each { |name| self.tags.append(Tag.find_or_create_by(name: name)) }
    end

    def parse_album
      if(album_name == '-1')
        album = Album.new
        album.update_attributes(:title => 'Default', :description => 'Default album for unsorted photos', :user_id => self.user.id)
        album.save
        self.album_id = album.id
      else
        self.album_id = self.album_name
      end
    end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :authenticate_user!
  load_and_authorize_resource
  
  def index
    @posts = Post.all.order('updated_at DESC')
    @best_posts = Post.all.sort_by(&:rating).reverse
    # rubocop:disable Metrics/LineLength
    @tags = Tag.all.sort { |tag2, tag1| Post.joins(:tags).where('tags.name' => tag1[:name]).count <=> Post.joins(:tags).where('tags.name' => tag2[:name]).count }
    # rubocop:enable Metrics/LineLength
  end

  def new
    @post = Post.new
    @albums = Album.where(user_id: current_user.id)
  end

  def edit
    @post = Post.find(params[:id])
    @albums = Album.where(user_id: @post.user_id)
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user
    @albums = Album.where(user_id: current_user.id)
    if @post.save
      redirect_to '/'
    else
      render 'new'
    end
  end

  # rubocop:disable Metrics/AbcSize
  def update
    @post = Post.find(params[:id])
    @albums = Album.where(user_id: @post.user_id)
    # rubocop:disable Style/SymbolProc
    old_tags = @post.tags.map { |tag| tag.name }.join(' ')
    # rubocop:enable Style/SymbolProc
    if @post.update(post_params)
      @post.check_tags(old_tags.split(/[\s,]+/))
      @post.update_attributes(album_id: post_params['album_name'])
      redirect_to '/'
    else
      render 'edit'
    end
  end
  # rubocop:enable Metrics/AbcSize

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    redirect_to '/'
  end

  # rubocop:disable Metrics/AbcSize
  def filter_best
    # rubocop:disable Metrics/LineLength
    @tags = Tag.all.sort { |tag2, tag1| Post.joins(:tags).where('tags.name' => tag1[:name]).count <=> Post.joins(:tags).where('tags.name' => tag2[:name]).count }
    # rubocop:enable Metrics/LineLength
    @posts = Post.joins(:tags).where('tags.name' => params[:tag_name]).sort_by(&:rating).reverse
    @active_tag = params[:tag_name]
    render :list_of_posts
  end
  # rubocop:enable Metrics/AbcSize


  # rubocop:disable Metrics/AbcSize
  def filter
    # rubocop:disable Metrics/LineLength
    @tags = Tag.all.sort { |tag2, tag1| Post.joins(:tags).where('tags.name' => tag1[:name]).count <=> Post.joins(:tags).where('tags.name' => tag2[:name]).count }
    # rubocop:enable Metrics/LineLength
    @posts = Post.joins(:tags).where('tags.name' => params[:tag_name]).order('updated_at DESC')
    @active_tag = params[:tag_name]
    render :list_of_posts
  end
  # rubocop:enable Metrics/AbcSize

  def show
    @post = Post.find(params[:id])
  end

  def best_posts
    @posts = Post.all.sort_by(&:rating).reverse
    # rubocop:disable Metrics/LineLength
    @tags = Tag.all.sort { |tag2, tag1| Post.joins(:tags).where('tags.name' => tag1[:name]).count <=> Post.joins(:tags).where('tags.name' => tag2[:name]).count }
    # rubocop:enable Metrics/LineLength
    render :list_of_posts
  end

  def newest_posts
    @posts = Post.all.order('updated_at DESC')
    # rubocop:disable Metrics/LineLength
    @tags = Tag.all.sort { |tag2, tag1| Post.joins(:tags).where('tags.name' => tag1[:name]).count <=> Post.joins(:tags).where('tags.name' => tag2[:name]).count }
    # rubocop:enable Metrics/LineLength
    render :list_of_posts
  end

  private

  def post_params
    params.require(:post).permit(:title, :description, :photo, :tags_string, :allow_comments, :album_name)
  end
end

app/helpers/posts_helper.rb
module PostsHelper

  def nested_comments(comments)
    comments.map do |comment, sub_comments|
      render(comment) + content_tag(:div, nested_comments(sub_comments), :class => "nested_comments")
    end.join.html_safe
  end

end

app/views/posts/edit.html.erb
<h1>Edit Post</h1>
<%= form_for :post, url: post_path(@post), method: :patch do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@post.errors.count, 'error') %> prohibited this post from being saved:
      </h2>
      <ul>
        <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p class="form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title, class:"form-control" %>
  </p>

  <p class="form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description, class:"form-control" %>
  </p>

  <p  class="form-group">
    <%= f.label :photo %><br>
    <%= image_tag @post.photo.url(:thumb) %><br />
    <%= f.file_field :photo %>
  </p>

  <p class="form-group">
    <%= f.label :tags_string %><br>
    <%= f.text_field :tags_string, :value => @post.tags.map{|tag| tag.name}.join(', '), class:"form-control"%>
  </p>

  <p class="form-group">
    <%= f.label :album %><br>
    <%= f.select(:album_name, options_for_select(@albums.map {|album| [album.title, album.id]}, :selected => @post.album_id), {}, {:class=>'form-control'}) %>
  </p>

  <p class="form-group">
    <%= f.label :allow_comments %><br>
    <%= f.select(:allow_comments, options_for_select([['Always', 'Always'], ['After approval', 'Approval'], ['Not Allowed', 'Never']], :selected => @post.allow_comments), {}, {:class=>'form-control'}) %>
  </p>

  <p>
    <%= f.submit class:"btn btn-success"%>
  </p>
<% end %>

app/views/posts/index.html.erb
<div>
  <div class="top_10_tags">
    <% Tag.top.limit(10).each do |tag| %>
        <%= link_to tag.name, filter_path(tag.name), :class=>"#{tag.name == @active_tag ? "active" : "not_active"}" %>
    <% end %>
    <button type="button" class="btn btn-info" data-toggle="collapse" data-target="#tags">More tags</button>
  </div>

  <div class="collapse" id="tags">
    <% Tag.top.offset(10).each do |tag| %>
        <%= link_to tag.name, filter_path(tag.name), :class=>"#{tag.name == @active_tag ? "active" : "not_active"}"%>
    <% end %>
  </div>
</div>


<br/>
<%= link_to 'Create new post', new_post_path, class: 'btn btn-success' %>
</br>
<div class="row">
<div class="col-lg-12">
    <h1 class="page-header text-left">Newest photos<%= link_to ' (all photos)', newest_posts_posts_path %></h1>
  </div>
      <% @posts.first(8).each do |post| %>
          <div class="col-lg-3 col-md-4 col-xs-6 thumb">

            <div class="thumbnail">
              <h4 class="picture_info"><%= post.title %></h4>
              <%= link_to (image_tag post.photo.url(:thumb)), post_path(post) %>
              <p class="picture_info"><%= post.description %></p>
              <div><% if can? :update, post %><%= link_to 'Edit', edit_post_path(post) %><% end %></div>
              <div><% if can? :delete, post %><%= link_to 'Delete', post_path(post),
                                                          method: :delete,
                                                          data: { confirm: 'Are you sure?' } %><% end %>
              </div>
            </div>
          </div>
          <% end %>
  <br>
  </div>

<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header text-left">Best photos <%= link_to ' (all photos)', best_posts_posts_path %></h1>
  </div>
      <% @best_posts.first(8).each do |post| %>
          <div class="col-lg-3 col-md-4 col-xs-6 thumb">

            <div class="thumbnail">
              <h4 class="picture_info"><%= post.title %></h4>
              <%= link_to (image_tag post.photo.url(:thumb)), post_path(post) %>
              <p class="picture_info"><%= post.description %></p>
              <div><% if can? :update, post %><%= link_to 'Edit', edit_post_path(post) %><% end %></div>
              <div><% if can? :delete, post %><%= link_to 'Delete', post_path(post),
                                                          method: :delete,
                                                          data: { confirm: 'Are you sure?' } %><% end %>
              </div>
            </div>
          </div>
          <% end %>
</div>

app/views/posts/list_of_posts.erb
<div>
  <div class="top_10_tags">
    <% Tag.top.limit(10).each do |tag| %>
        <%= link_to tag.name, action_name == 'best_posts' || action_name == 'filter_best' ? filter_best_path(tag.name) : filter_path(tag.name), :class=>"#{tag.name == @active_tag ? "active" : "not_active"}" %>
    <% end %>
    <button type="button" class="btn btn-info" data-toggle="collapse" data-target="#tags">More tags</button>
  </div>

  <div class="collapse" id="tags">
    <% Tag.top.offset(10).each do |tag| %>
        <%= link_to tag.name, action_name == 'best_posts' || action_name == 'filter_best' ? filter_best_path(tag.name) : filter_path(tag.name), :class=>"#{tag.name == @active_tag ? "active" : "not_active"}"%>
    <% end %>
  </div>
</div>

<br/>
<br/>
<%= link_to 'Create new post', new_post_path, class: 'btn btn-success' %>
</br>
<br/>
<div class="row">

  <div class="col-lg-12">

<table class="table">
  <tr>
    <th>Author</th>
    <th>Title</th>
    <th>Description</th>
    <th>Photo</th>
    <th>Album</th>
    <th>Tags</th>
  </tr>

  <% @posts.each do |post| %>
    <tr id="post-row-<%= post.id %>">
      <td class="post-author"><%= image_tag post.user.avatar.url(:thumb) %> <p><%= link_to post.user.email, user_show_path(post.user.id) %></p></td>
      <td class="post-title"><p class="picture_info"><%= post.title %></p></td>
      <td class="post-description"><p class="picture_info"><%= post.description %></p></td>
      <td class="post-photo"><%= image_tag post.photo.url(:thumb) %></td>
      <td class="post-title"><%= link_to post.album.title, album_path(post.album) unless post.album.nil? %></td>
      <td class="post-tags "><p class="picture_info"><%= post.tags.map { |tag| tag.name}.join(', ') %></p></td>
      <td class="post-comments"><%= post.allow_comments %></td>
      <% if can? :update, post %><td><%= link_to 'Edit', edit_post_path(post) %></td><% end %>
      <% if can? :delete, post %><td><%= link_to 'Delete', post_path(post),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td><% end %>
      <% if can? :read, post %><td><%= link_to 'Show', post_path(post) %></td><% end %>
    </tr>
  <% end %>
</table>
</div>
</div>

app/views/posts/new.html.erb
<h1>New Post</h1>
<%= form_for :post, url:posts_path do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@post.errors.count, 'error') %> prohibited this post from being saved:
      </h2>
      <ul>
        <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p class="form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title, class:"form-control" %>
  </p>

  <p class="form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description, class:"form-control" %>
  </p>

  <p class="form-group">
    <%= f.label :photo %><br />
    <%= f.file_field :photo %>
  </p>

  <p class="form-group">
    <%= f.label :tags_string %><br>
    <%= f.text_field :tags_string, class:"form-control" %>
  </p>
  
  <p class="form-group">
    <%= f.label :album %><br>
    <%= f.select(:album_name, options_for_select(@albums.present? ? @albums.map {|album| [album.title, album.id]} :[['Default', '-1']]), {}, { :class => "form-control" }) %>
  </p>

  <p class="form-group">
    <%= f.label :allow_comments %><br>
    <%= f.select(:allow_comments, options_for_select([['Always', 'Always'], ['After approval', 'Approval'], ['Not Allowed', 'Never']]), {}, { :class => "form-control" }) %>
  </p>
 
  <p class="form-group">
    <%= f.submit "Save post", class:"btn btn-success"  %>
  </p>
<% end %>

app/views/posts/show.html.erb
<p>
  <%= rating_for @post, 'quality', star_path: '/images/ratyrate'%>
</p>

<p>
  <strong>Author:</strong>
  <%= @post.user.email %>
</p>

<p>
  <h3><%= @post.title %></h3>
</p>

<p>
  <%= @post.description %>
</p>

<p>
  <%= link_to @post.photo.url, :target => "_blank" do %>
      <%= image_tag @post.photo.url(:medium) %>
  <% end %>
</p>
<% if can? :update, @post %>
    <td><%= link_to 'Edit', edit_post_path(@post), class: "btn btn-info" %></td>
<% end %>
<% if can? :delete, @post %>
    <td><%= link_to 'Delete', post_path(@post),
                    method: :delete,
                    data: {confirm: 'Are you sure?'}, class: "btn btn-danger" %></td>
<% end %>

<br>
<br>
<p><b>Tags: </b>
  <%@post.tags.each do |tag| %>
      <%= link_to tag.name, filter_path(tag.name), :class=> 'filter-by-tag'%>
  <% end %>
</p>

<% unless @post.allow_comments == "Never" %>
<hr>
<h3>Add a comment:</h3>
<%= form_for([@post, @post.comments.build]) do |f| %>

    <p class="form-group">
      <%= f.label :body %><br>
      <%= f.text_area :body, class: "form-control" %>
    </p>
    <p class="form-group">
      <%= f.submit value:"Post Comment", class: "btn btn-success" %>
    </p>
<% end %>
<hr>
<h3>Comments</h3>


<div class="container comment_cont">
  <div class="row">
    <div class="col-md-8">
      <section class="comment-list">
        <!-- First Comment -->

        <%= nested_comments @post.comments.arrange(:order => :created_at) %>
      </section>
    </div>
  </div>
</div>
<% end %>