config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  devise_for :users
  root 'posts#index'

  resources :users do
    get "show"
    patch 'change_admin'
  end

  resources :posts do
    get 'best_posts', on: :collection
    get 'newest_posts', on: :collection
    resources :comments do
      patch "like"
      patch "dislike"
      patch "toggle_visible"
      patch "toggle_valid"
    end
  end
  
  resources :albums do
    match :posts, via: [:get, :patch], on: :member#get 'posts_list', :as => 'posts_list'
  end

  get 'posts/filter/:tag_name' => 'posts#filter', as: 'filter'

   get 'posts/filter_best/:tag_name' => 'posts#filter_best', as: 'filter_best'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ruby Foto blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
</head>
<body>
<!-- Navigation -->
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <% if user_signed_in? %>
      <%= link_to 'Home', posts_path, class: "navbar-brand" %>
      <% end %>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <% if user_signed_in? %>
        <li>
          <%= link_to 'Best photos', best_posts_posts_path %>
        </li>
        <li>
          <%= link_to 'Newest photos', newest_posts_posts_path %>
        </li>
        <li>
          <%= link_to current_user.admin? ? 'Albums' : 'My albums', albums_path %>
        </li>
          <li>
            <%= link_to 'Edit profile', '/users/edit' %>
          </li>
          <% if current_user.admin? %>
            <li>
              <%= link_to 'Users', users_path %>
            </li>
          <% end %>
          <li>
            <%= link_to 'Log out (' + current_user.email + ')', destroy_user_session_path, method: :delete  %>
          </li>
        <% else %>
          <li>
            <%= link_to "Log in", new_user_session_path %>
          </li>
        <% end %>
      </ul>
    </div>
    <!-- /.navbar-collapse -->
  </div>
  <!-- /.container -->
</nav>

<br />
<br />
<div class="container">
  <div class="col-md-8 col-md-offset-2">
    <% unless notice ==nil %> <p class="alert alert-info text-center"><%= notice %></p> <% end %>
    <% unless alert ==nil %> <p class="alert alert-danger text-center"><%= alert %></p> <% end %>
    <br />
    <div style="text-align: center; margin:auto;">
      <%= yield %>
    </div>
  </div>
</div>

<footer></footer>
</body>
</html>